#!/bin/sh
#
# script/release: Deploy maven artifact in current directory to Maven central
#                 repository using maven-release-plugin

set -e

read -p "Release to maven central repository (yes/no)? "

if ( [ "$REPLY" == "yes" ] ) then
  DATE=$(date +"%Y-%m-%d-%H-%M-%S")
  mvn clean deploy -P release -B -e | tee "tmp/$DATE-release.log"
else
  echo "You've opted not to release, exiting..."
fi
